spring.application.name=GymFlow

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/gymflow
spring.datasource.username=gymflow
spring.datasource.password=gymflow
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#Spring Security
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

# Timezone
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo
